### ISSUE TITLE
 could not find function "post_bsky"

### ISSUE THREAD

**Issue by jobreu** [cjbarrie/blueskyr#2]
Apologies if this comes too early or has already been solved! Feel free to simply ignore or close this issue in that case.

I got the installation to work but when I run `post_bsky()`, I get the error message "could not find function "post_bsky"".

As a haphazard trouble-shooting attempt, I defined the functions from the R folder (`get_request`, `get_session`, `post_bsky`) locally but then got "Error in get_session(method = "POST") : object 'session' not found" when running `post_bsky()`.

If I just run either `get_request()` or `get_session()`, I get "argument "method" is missing, with no default".

Sorry for my somewhat unstructured issue! I hope this is still useful.

**Comment by cjbarrie** [comment]
Missed out export line. Now fixed. Thanks for this.

**Comment by jobreu** [comment]
Thanks! Can confirm that the function works now. See: https://bsky.app/profile/jobreu.bsky.social/post/3kaeso66bjl2h
